name: stockfish
description: The Stockfish Chess Engine for Flutter.
version: 1.7.2
repository: https://github.com/ArjanAswal/stockfish.git
homepage: https://github.com/ArjanAswal/stockfish.git

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  ffi: ^2.0.0
  flutter:
    sdk: flutter
  logging: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.stockfish
        pluginClass: StockfishPlugin
      ios:
        pluginClass: StockfishPlugin
